export const pessoa = [
    {
        chave: "aline",
        nome: "Aline",
        sobrenome: "Rosario",
        ramal: 4801,
        email: "aline@mhedica.com.br",
        numero: 31984827056,
        cargo: "Analista de Faturamento Júnior",
        setor: "Comercial",
        admissao: "01/09/2015",
        aniversario: "18/03/1983",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Aline.jpg",
    },
    {
        chave: "brenda",
        nome: "Brenda",
        sobrenome: "Costa",
        ramal: 4807,
        email: "brenda@mhedica.com.br",
        numero: 31997207340,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "01/10/2020",
        aniversario: "17/02/1994",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Brenda.jpg",
    },
    {
        chave: "bruno",
        nome: "Bruno",
        sobrenome: "Varandas",
        ramal: 4810,
        email: "bruno.varandas@mhedica.com.br",
        numero: 31971495144,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "23/08/2021",
        aniversario: "05/07/1985",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Bruno.jpg",
    },
    {
        chave: "carlos",
        nome: "Carlos",
        sobrenome: "Henrique",
        ramal: 4799,
        email: "carlos@mhedica.com.br",
        numero: 3199749739,
        cargo: "Analista Comercial Junior",
        setor: "Comercial",
        admissao: "03/12/2018",
        aniversario: "18/04/1994",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Carlos-1.jpg",
    },
    {
        chave: "clara",
        nome: "Clara",
        sobrenome: "Aida",
        ramal: 4804,
        email: "marketing@mhedica.com.br",
        numero: 31996751143,
        cargo: "Auxiliar de Marketing",
        setor: "Marketing",
        admissao: "01/07/2021",
        aniversario: "01/04/2009",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Clara.jpg",
    },
    {
        chave: "claudio",
        nome: "Claudio",
        sobrenome: "Teixeira",
        ramal: 4809,
        email: "claudio@mhedica.com.br",
        numero: 31984896457,
        cargo: "Gerente de Serviços",
        setor: "Assistência Técnica",
        admissao: "01/04/2009",
        aniversario: "22/05/1978",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Claudio.jpg",
    },
    {
        chave: "douglas",
        nome: "Douglas",
        sobrenome: "Robert",
        ramal: 4791,
        email: "douglas@mhedica.com.br",
        numero: 31984826733,
        cargo: "Diretor Técnico",
        setor: "Assistência Técnica",
        admissao: null,
        aniversario: "23/03/1976",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Douglas.jpg",
    },
    {
        chave: "eduardo",
        nome: "Eduardo",
        sobrenome: "Benedicto",
        ramal: 4792,
        email: "eduardo@mhedica.com.br",
        setor: "Assistência Técnica",
        numero: 31997156077,
        cargo: "Consultor de Vendas",
        admissao: "04/06/2018",
        aniversario: "04/01/1982",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Eduardo-Benedicto-.jpg",
    },
    {
        chave: "eduardo-rangel",
        nome: "Eduardo",
        sobrenome: "Rangel",
        ramal: 4805,
        email: "eduardo.rangel@mhedica.com.br",
        numero: 31998949613,
        cargo: "Auxiliar de Logística",
        setor: "Almoxarifado",
        admissao: "04/02/2022",
        aniversario: "23/03/1986",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Eduardo-Rangel.jpg",
    },
    {
        chave: "elizangela",
        nome: "Elizangela",
        sobrenome: "Leles",
        ramal: 4800,
        email: "elizangela@mhedica.com.br",
        numero: 31999618153,
        cargo: "Auxiliar Comercial",
        setor: "Comercial",
        admissao: "03/08/2021",
        aniversario: "06/08/1994",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Elizangela-1.jpg",
    },
    {
        chave: "eugenio",
        nome: "Eugênio",
        sobrenome: "Pacelli",
        ramal: 4804,
        email: "eugenio@mhedica.com.br",
        numero: 31995530963,
        cargo: "Supervisor de Tecnologia",
        setor: "TI",
        admissao: "02/05/2019",
        aniversario: "25/06/1988",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Eugenio.jpg",
    },
    {
        chave: "fabio",
        nome: "Fábio",
        sobrenome: "Pitzer",
        ramal: "Sem Ramal",
        email: "fabio@mhedica.com.br",
        numero: 31999868900,
        cargo: "Técnico de Imagem 2",
        setor: "Assistência Técnica",
        admissao: "13/09/2021",
        aniversario: "05/01/1979",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Fabio.jpg",
    },
    {
        chave: "fernanda-moreira",
        nome: "Fernanda",
        sobrenome: "Moreira",
        ramal: 4795,
        email: "fernanda.moreira@mhedica.com.br",
        numero: null,
        cargo: "Assistente Financeiro",
        setor: "Financeiro",
        admissao: null,
        aniversario: null,
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/03/Fernanda-Moreira.jpg",
    },
    {
        chave: "fernanda",
        nome: "Fernanda",
        sobrenome: "Rodrigues",
        ramal: 4796,
        email: "fernanda@mhedica.com.br",
        numero: 31971706023,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "28/10/2019",
        aniversario: "11/05/1985",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Fernanda.jpg",
    },
    {
        chave: "glauber",
        nome: "Glauber",
        sobrenome: "Sales",
        ramal: 4807,
        email: "glauber@mhedica.com.br",
        numero: 31983123108,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "02/01/2014",
        aniversario: "12/08/1985",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Glauber.jpg",
    },
    {
        chave: "glauciene",
        nome: "Glauciene",
        sobrenome: "Silva",
        ramal: 4795,
        email: "glauciene@mhedica.com.br",
        numero: 31998797328,
        cargo: "Analista Financeiro",
        setor: "Financeiro",
        admissao: "02/01/2020",
        aniversario: "01/03/1983",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Glauciene.jpg",
    },
    {
        chave: "jacimara",
        nome: "Jacimara",
        sobrenome: "Nogueira",
        ramal: 4792,
        email: "jacimara@mhedica.com.br",
        numero: 31997553899,
        cargo: "Técnico de Imagem 1",
        setor: "Assistência Técnica",
        admissao: "01/10/2020",
        aniversario: "18/04/1994",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Jacimara.jpg",
    },
    {
        chave: "jane",
        nome: "Jane",
        sobrenome: "Mota",
        ramal: 4790,
        email: "recepcao@mhedica.com.br",
        numero: "Sem número",
        cargo: "Recepcionista",
        setor: "Recepção",
        admissao: "02/10/2017",
        aniversario: "27/03/1985",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Jane.jpg",
    },
    {
        chave: "juan",
        nome: "Juan",
        sobrenome: "Bentes",
        ramal: 4792,
        email: "juan@mhedica.com.br",
        numero: 31999853851,
        cargo: "Técnico Júnior 2",
        setor: "Assistência Técnica",
        admissao: "20/05/2019",
        aniversario: "17/02/1989",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Juan.jpg",
    },
    {
        chave: "larissa",
        nome: "Larissa",
        sobrenome: "Pereira",
        ramal: 4792,
        email: "larissa@mhedica.com.br",
        numero: 31984674849,
        cargo: "Auxiliar Administrativo 2",
        setor: "Assistência Técnica",
        admissao: "02/03/2020",
        aniversario: "13/06/1996",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Larissa.jpg",
    },
    {
        chave: "leandro",
        nome: "Leandro",
        sobrenome: "Gonçalves",
        ramal: 4805,
        email: "leandro@mhedica.com.br",
        numero: 31996181294,
        cargo: "Auxiliar de Estoque",
        setor: "Almoxarifado",
        admissao: "02/08/2021",
        aniversario: "13/09/1986",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Leandro.jpg",
    },
    {
        chave: "leticia",
        nome: "Letícia",
        sobrenome: "Sette Câmara",
        ramal: 4806,
        email: "leticia@mhedica.com.br",
        numero: "Sem número",
        cargo: "Assistente Financeiro",
        setor: "Financeiro",
        admissao: "01/03/2021",
        aniversario: "08/12/2000",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Leticia.jpg",
    },
    {
        chave: "liliana",
        nome: "Liliana",
        sobrenome: "Espíndola",
        ramal: 4811,
        email: "liliana@mhedica.com.br",
        numero: 31996761564,
        cargo: "Consultora de Vendas",
        setor: "Vendas",
        admissao: "10/01/2022",
        aniversario: "04/08/1958",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Liliana.jpg",
    },
    {
        chave: "lorena",
        nome: "Lorena",
        sobrenome: "Rodrigues",
        ramal: 4805,
        email: "almoxarifado@mhedica.com.br",
        numero: 31984826796,
        cargo: "Auxiliar de Almoxarifado",
        setor: "Almoxarifado",
        admissao: "26/04/2021",
        aniversario: "31/08/1996",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Lorena.jpg",
    },
    {
        chave: "luana",
        nome: "Luana",
        sobrenome: "Morelle",
        ramal: 4806,
        email: "rh@mhedica.com.br",
        numero: null,
        cargo: "Analista de RH",
        setor: "Recursos Humanos",
        admissao: null,
        aniversario: null,
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/03/Luana.jpg",
    },
    {
        chave: "lucas-araujo",
        nome: "Lucas",
        sobrenome: "Araújo",
        ramal: 4808,
        email: "lucas.araujo@mhedica.com.br",
        numero: 31983989169,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "10/01/2022",
        aniversario: "09/06/1984",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Lucas-Araujo.jpg",
    },
    {
        chave: "lucas-henrique",
        nome: "Lucas",
        sobrenome: "Henrique",
        ramal: 4805,
        email: "lucas.henrique@mhedica.com.br",
        numero: 31997209866,
        cargo: "Coordenador de Estoque",
        setor: "Almoxarifado",
        admissao: "02/04/2020",
        aniversario: "30/06/1995",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Lucas-Henrique.jpg",
    },
    {
        chave: "lucas-mendonca",
        nome: "Lucas",
        sobrenome: "Mendonça",
        ramal: 4811,
        email: "lucas.mendonca@mhedica.com.br",
        numero: 31983999710,
        cargo: "Gerente de Vendas",
        setor: "Vendas",
        admissao: "01/10/2020",
        aniversario: "26/11/1991",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Lucas-Mendonca.jpg",
    },
    {
        chave: "marcos-faria",
        nome: "Marcos",
        sobrenome: "Faria",
        ramal: 4796,
        email: "marcos.faria@mhedica.com.br",
        numero: 31995403566,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "25/10/2021",
        aniversario: "19/11/1984",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Marcos-Faria.jpg",
    },
    {
        chave: "marcos-ferreira",
        nome: "Marcos",
        sobrenome: "Ferreira",
        ramal: 4798,
        email: "marcos@mhedica.com.br",
        numero: 31983840430,
        cargo: "Especialista de Produtos Junior",
        setor: "Comercial",
        admissao: "31/08/2020",
        aniversario: "09/03/1986",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Marcos-Ferreira.jpg",
    },
    {
        chave: "marcus-fantoni",
        nome: "Marcus",
        sobrenome: "Fantoni",
        ramal: 4804,
        email: "marcus.fantoni@mhedica.com.br",
        numero: 31984666714,
        cargo: "Gerente de Vendas Imagem",
        setor: "Vendas",
        admissao: "15/09/2021",
        aniversario: "26/03/1970",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Marcus-Fantoni.jpg",
    },
    {
        chave: "mercia",
        nome: "Mércia",
        sobrenome: "Carmo",
        ramal: 4815,
        email: "qualidade@mhedica.com.br",
        numero: 31990606312,
        cargo: "Responsável Técnica | Farmaceutica",
        setor: "Qualidade",
        admissao: "07/02/2022",
        aniversario: "04/05/1982",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Mercia.jpg",
    },
    {
        chave: "napoleao",
        nome: "Napolão",
        sobrenome: "Sorbello",
        ramal: 4794,
        email: "napoleao@mhedica.com.br",
        numero: 31984826747,
        cargo: "CEO",
        setor: "Diretoria",
        admissao: null,
        aniversario: "16/03/1956",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Napoleao.jpg",
    },
    {
        chave: "nayara",
        nome: "Nayara",
        sobrenome: "Fuchs",
        ramal: 4803,
        email: "nayara@mhedica.com.br",
        numero: 31984827062,
        cargo: "Gerente Comercial",
        setor: "Comercial",
        admissao: "05/11/2014",
        aniversario: "07/08/1983",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Nayara.jpg",
    },
    {
        chave: "paulo",
        nome: "Paulo",
        sobrenome: "Lucas",
        ramal: 4804,
        email: "paulo@mhedica.com.br",
        numero: null,
        cargo: "Auxiliar de TI",
        setor: "TI",
        admissao: "14/02/2022",
        aniversario: "28/11/2001",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Paulo.jpg",
    },
    {
        chave: "poliana",
        nome: "Poliana",
        sobrenome: "Candelária",
        ramal: 4813,
        email: "poliana@mhedica.com.br",
        numero: 31984664732,
        cargo: "Analista de Licitação",
        setor: "Comercial",
        admissao: "08/11/2021",
        aniversario: "05/02/1988",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Poliana.jpg",
    },
    {
        chave: "rafael-danilo",
        nome: "Rafael",
        sobrenome: "Danilo",
        ramal: 4814,
        email: "rafael.danilo@mhedica.com.br",
        numero: "Sem número",
        cargo: "Especialista Fiscal",
        setor: "Comercial",
        admissao: "23/11/2021",
        aniversario: "25/01/1991",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Rafael-Danilo.jpg",
    },
    {
        chave: "rafael-sorbello",
        nome: "Rafael",
        sobrenome: "Sorbello",
        ramal: 4793,
        email: "rafael@mhedica.com.br",
        numero: 31984543952,
        cargo: "Diretor de Vendas",
        setor: "Diretoria",
        admissao: null,
        aniversario: "28/04/1982",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Rafael.jpg",
    },
    {
        chave: "rafaela",
        nome: "Rafaela",
        sobrenome: "Santos",
        ramal: 4796,
        email: "rafaela@mhedica.com.br",
        numero: 31998007520,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "11/02/2019",
        aniversario: "10/08/1989",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Rafaela.jpg",
    },
    {
        chave: "ricardo",
        nome: "Ricardo",
        sobrenome: "Dutra",
        ramal: 4810,
        email: "ricardo@mhedica.com.br",
        numero: 31984826706,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "03/02/2020",
        aniversario: "18/01/1976",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Ricardo.jpg",
    },
    {
        chave: "rubens",
        nome: "Rubens",
        sobrenome: "Bentes",
        ramal: 4809,
        email: "rubens@mhedica.com.br",
        numero: 31990606251,
        cargo: "Técnico Junior 2",
        setor: "Assistência Técnica",
        admissao: "31/01/2022",
        aniversario: "05/08/1986",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Rubens.jpg",
    },
    {
        chave: "sidney",
        nome: "Sidney",
        sobrenome: "Castro",
        ramal: 4807,
        email: "sidney@mhedica.com.br",
        numero: 31998500345,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "14/10/2021",
        aniversario: "19/10/1976",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Sidney.jpg",
    },
    {
        chave: "silvia",
        nome: "Silvia",
        sobrenome: "Paixão",
        ramal: 4802,
        email: "silvia@mhedica.com.br",
        numero: 31996987518,
        cargo: "Supervisora Comercial",
        setor: "Comercial",
        admissao: "08/09/2017",
        aniversario: "30/04/1979",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Silvia.jpg",
    },
    {
        chave: "stefanie",
        nome: "Stefanie",
        sobrenome: "Sorbello",
        ramal: 4797,
        email: "stefanie@mhedica.com.br",
        numero: 31984826926,
        cargo: "Diretora de Operações",
        setor: "Diretoria | Comercial",
        admissao: null,
        aniversario: "06/10/1986",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Stefanie.jpg",
    },
    {
        chave: "thais",
        nome: "Thais",
        sobrenome: "Barroso",
        ramal: "Sem Ramal",
        email: "thais@mhedica.com.br",
        numero: 31984001861,
        cargo: "Consultora de Vendas",
        setor: "Vendas",
        admissao: "05/10/2020",
        aniversario: "09/12/1994",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Thais.jpg",
    },
    {
        chave: "victor",
        nome: "Victor",
        sobrenome: "Hugo",
        ramal: 4792,
        email: "victor@mhedica.com.br",
        numero: 31984826752,
        cargo: "Técnico Junior 2",
        setor: "Assistência Técnica",
        admissao: "01/08/2009",
        aniversario: "19/11/1977",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Victor.jpg",
    },
    {
        chave: "wander",
        nome: "Wander",
        sobrenome: "Amendoeira",
        ramal: 4812,
        email: "wander@mhedica.com.br",
        numero: 31997414354,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "05/10/2020",
        aniversario: "26/12/1962",
        foto: "https://www.mhedica.com.br/wp-content/uploads/2022/02/Wander.jpg",
    },
]