export const pessoa = [
    {
        chave: "aline",
        nome: "Aline",
        sobrenome: "Rosario",
        ramal: 4801,
        email: "aline@mhedica.com.br",
        numero: 31984827056,
        cargo: "Analista de Faturamento Pleno",
        setor: "Comercial",
        admissao: "01/09/2015",
        aniversario: "03/18/1983",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/aline.png?alt=media&token=608903a1-fe59-4959-bb53-cd19cc9ae49f",
    },
    {
        chave: "antonio",
        nome: "Antonio",
        sobrenome: "Souza",
        ramal: 4807,
        email: "antonio@mhedica.com.br",
        numero: 31995373113,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "18/04/2022",
        aniversario: "09/01/1985",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/antonio.png?alt=media&token=f71cc030-bb9b-41d8-8ea2-766707b39e01",
    },
    {
        chave: "brenda",
        nome: "Brenda",
        sobrenome: "Costa",
        ramal: 4807,
        email: "brenda@mhedica.com.br",
        numero: 31997207340,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "01/10/2020",
        aniversario: "17/02/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/brenda.png?alt=media&token=977d6ef9-9f41-4177-9206-29fe1e145216",
    },
    {
        chave: "bruno",
        nome: "Bruno",
        sobrenome: "Varandas",
        ramal: 4810,
        email: "bruno.varandas@mhedica.com.br",
        numero: 31971495144,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "23/08/2021",
        aniversario: "07/05/1985",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/bruno.png?alt=media&token=de8e1e53-7b83-4423-a2ae-8fcd9feb72d8",
    },
    {
        chave: "carlos",
        nome: "Carlos",
        sobrenome: "Henrique",
        ramal: 4799,
        email: "carlos@mhedica.com.br",
        numero: 31997490739,
        cargo: "Coordenador de Vendas",
        setor: "Comercial",
        admissao: "03/12/2018",
        aniversario: "04/18/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/carlos.png?alt=media&token=d179cea9-8b9a-458b-88bc-105ec1fb3d57",
    },
    {
        chave: "cileia",
        nome: "Ciléia",
        sobrenome: "Gonçalves",
        ramal: 4806,
        email: "cileia@mhedica.com.br",
        numero: 31996219343,
        cargo: "Analista Contábil",
        setor: "Financeiro",
        admissao: "03/21/2022",
        aniversario: "02/05/1972",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/cileia.png?alt=media&token=cb23b5ac-5076-40a8-b5ce-87c674f9d393",
    },
    {
        chave: "claudio-teixeira",
        nome: "Claudio",
        sobrenome: "Teixeira",
        ramal: 4809,
        email: "claudio@mhedica.com.br",
        numero: 31984896457,
        cargo: "Gerente de Serviços Pleno",
        setor: "Assistência Técnica",
        admissao: "01/04/2009",
        aniversario: "05/22/1978",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/claudio.png?alt=media&token=6a0abbc8-3ca6-4a54-9c99-b454abba5608",
    },
    {
        chave: "douglas",
        nome: "Douglas",
        sobrenome: "Robert",
        ramal: 4791,
        email: "douglas@mhedica.com.br",
        numero: 31984826733,
        cargo: "Diretor Técnico",
        setor: "Assistência Técnica",
        admissao: null,
        aniversario: "03/23/1976",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/douglas.png?alt=media&token=a2dde48c-54a0-4c11-9232-6970a2eab875",
    },
    {
        chave: "eduardo-benedicto",
        nome: "Eduardo",
        sobrenome: "Benedicto",
        ramal: 4792,
        email: "eduardo@mhedica.com.br",
        setor: "Assistência Técnica",
        numero: 31997156077,
        cargo: "Consultor de Vendas",
        admissao: "04/06/2018",
        aniversario: "01/04/1982",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/eduardo-benedicto.png?alt=media&token=86912d3d-ab8e-4b52-b03e-4f9efd25ed72",
    },
    {
        chave: "eduardo-rangel",
        nome: "Eduardo",
        sobrenome: "Rangel",
        ramal: 4796,
        email: "eduardo.rangel@mhedica.com.br",
        numero: 31998949613,
        cargo: "Analista de Logística Jr",
        setor: "Almoxarifado",
        admissao: "04/02/2022",
        aniversario: "03/23/1986",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/eduardo-rangel.png?alt=media&token=c1ef6a9e-f85c-4c40-b764-d511c1208baa",
    },
    {
        chave: "elizangela",
        nome: "Elizangela",
        sobrenome: "Leles",
        ramal: 4800,
        email: "elizangela@mhedica.com.br",
        numero: 31999618153,
        cargo: "Assistênte Comercial Júnior",
        setor: "Comercial",
        admissao: "03/08/2021",
        aniversario: "08/06/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/elizangela.png?alt=media&token=8a42805e-268a-4cf3-ace7-47a03bfed3a5",
    },
    {
        chave: "eugenio",
        nome: "Eugênio",
        sobrenome: "Pacelli",
        ramal: 4804,
        email: "eugenio@mhedica.com.br",
        numero: 31995530963,
        cargo: "Supervisor de TI Pleno",
        setor: "TI",
        admissao: "02/05/2019",
        aniversario: "06/25/1988",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/eugenio.png?alt=media&token=9dee448a-eb6a-4726-a14b-f0fa8e86d0f9",
    },
    {
        chave: "fabio",
        nome: "Fábio",
        sobrenome: "Pitzer",
        ramal: "Sem Ramal",
        email: "fabio@mhedica.com.br",
        numero: 31999868900,
        cargo: "Técnico de Imagem 2",
        setor: "Assistência Técnica",
        admissao: "13/09/2021",
        aniversario: "01/05/1979",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/fabio.png?alt=media&token=e968988e-cea3-42a6-b2bc-6d0389c2be32",
    },
    {
        chave: "fernanda-moreira",
        nome: "Fernanda",
        sobrenome: "Moreira",
        ramal: 4795,
        email: "fernanda.moreira@mhedica.com.br",
        numero: 31998797328,
        cargo: "Assistente Financeiro",
        setor: "Financeiro",
        admissao: "03/03/2022",
        aniversario: "09/03/1999",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/fernanda-moreira.png?alt=media&token=e7ed86a1-79af-4a8a-a248-5d0d776e2881",
    },
    {
        chave: "fernanda-rodrigues",
        nome: "Fernanda",
        sobrenome: "Rodrigues",
        ramal: 4807,
        email: "fernanda@mhedica.com.br",
        numero: 31971706023,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "28/10/2019",
        aniversario: "05/11/1985",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/fernanda-rodrigues.png?alt=media&token=ca0ba0b7-0d22-4000-844c-8f141e108a95",
    },
    {
        chave: "gabriella",
        nome: "Gabriella",
        sobrenome: "de Freitas",
        ramal: null,
        email: "gabriella@mhedica.com.br",
        numero: 31996181294,
        cargo: "Assistente Comercial Junior",
        setor: "Comercial",
        admissao: "10/10/2022",
        aniversario: "01/06/1993",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/gabriella.png?alt=media&token=cd94c6bf-0f68-4444-b750-ae3304d1b891",
    },
    {
        chave: "glauber",
        nome: "Glauber",
        sobrenome: "Sales",
        ramal: 4807,
        email: "glauber@mhedica.com.br",
        numero: 31983123108,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "02/01/2014",
        aniversario: "08/12/1985",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/glauber.png?alt=media&token=cce8adef-50d7-4817-8873-80fe97e55126",
    },
    {
        chave: "glauciene",
        nome: "Glauciene",
        sobrenome: "Silva",
        ramal: 4795,
        email: "glauciene@mhedica.com.br",
        numero: 31990606231,
        cargo: "Analista Financeiro Senior",
        setor: "Financeiro",
        admissao: "02/01/2020",
        aniversario: "03/01/1983",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/glauciene.png?alt=media&token=c55f83dd-0edd-4df4-9c8b-f8abcd668c5b",
    },
    {
        chave: "italo",
        nome: "Ítalo",
        sobrenome: "Guilherme",
        ramal: 4804,
        email: "marketing@mhedica.com.br",
        numero: 31996751143,
        cargo: "Auxiliar de Marketing",
        setor: "Marketing",
        admissao: "05/05/2022",
        aniversario: "08/19/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/italo.png?alt=media&token=a08e3db8-7b05-4ee6-9e06-34c282b71ae8",
    },
    {
        chave: "jacimara",
        nome: "Jacimara",
        sobrenome: "Nogueira",
        ramal: 4792,
        email: "jacimara@mhedica.com.br",
        numero: 31997553899,
        cargo: "Técnica de Imagem Pleno",
        setor: "Assistência Técnica",
        admissao: "01/10/2020",
        aniversario: "04/18/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/jacimara.png?alt=media&token=39698bd3-5c12-4c6e-8b4d-1fd2afebce15",
    },
    {
        chave: "jane",
        nome: "Jane",
        sobrenome: "Mota",
        ramal: 4790,
        email: "recepcao@mhedica.com.br",
        numero: 31999223482,
        cargo: "Secretária Executiva",
        setor: "Recepção",
        admissao: "02/10/2017",
        aniversario: "03/27/1985",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/jane.png?alt=media&token=4bca5127-caf3-4507-82d8-200a5597f7ce",
    },
    {
        chave: "juan",
        nome: "Juan",
        sobrenome: "Bentes",
        ramal: 4792,
        email: "juan@mhedica.com.br",
        numero: 31999853851,
        cargo: "Técnico Júnior 2",
        setor: "Assistência Técnica",
        admissao: "20/05/2019",
        aniversario: "02/17/1989",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/juan.png?alt=media&token=a1851c18-5b8f-4f50-902b-08896fe6f132",
    },
    {
        chave: "larissa",
        nome: "Larissa",
        sobrenome: "Pereira",
        ramal: 4792,
        email: "larissa@mhedica.com.br",
        numero: 31984674849,
        cargo: "Auxiliar Administrativo Pleno",
        setor: "Assistência Técnica",
        admissao: "02/03/2020",
        aniversario: "06/13/1996",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/larissa.png?alt=media&token=44b48f63-c52d-4580-a042-a2b864ee3dd9",
    },
    {
        chave: "leticia",
        nome: "Letícia",
        sobrenome: "Sette Câmara",
        ramal: 4808,
        email: "leticia@mhedica.com.br",
        numero: 31997738551,
        cargo: "Compradora Junior",
        setor: "Financeiro",
        admissao: "01/03/2021",
        aniversario: "12/08/2000",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/leticia.png?alt=media&token=55fe6c08-e784-4b08-ba12-f626ac714829",
    },
    {
        chave: "luana",
        nome: "Luana",
        sobrenome: "Morelle",
        ramal: 4806,
        email: "rh@mhedica.com.br",
        numero: 31998820889,
        cargo: "Analista de RH Pleno",
        setor: "Recursos Humanos",
        admissao: "03/03/2022",
        aniversario: "03/26/1988",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/luana.png?alt=media&token=08bb6a7a-a4e9-4d48-a7c5-35d06319ba31",
    },
    {
        chave: "lucas-araujo",
        nome: "Lucas",
        sobrenome: "Araújo",
        ramal: 4808,
        email: "lucas.araujo@mhedica.com.br",
        numero: 31983989169,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "10/01/2022",
        aniversario: "06/09/1984",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/lucas-araujo.png?alt=media&token=c4e5ddf8-9b4f-4a50-9bb8-6d5c8f08994d",
    },
    {
        chave: "lucas-henrique",
        nome: "Lucas",
        sobrenome: "Henrique",
        ramal: 4796,
        email: "lucas.henrique@mhedica.com.br",
        numero: 31997209866,
        cargo: "Coordenador de Estoque",
        setor: "Almoxarifado",
        admissao: "02/04/2020",
        aniversario: "06/30/1995",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/lucas-henrique.png?alt=media&token=44796815-f03f-4432-be4c-167440cb3cc7",
    },
    {
        chave: "lucas-mendonca",
        nome: "Lucas",
        sobrenome: "Mendonça",
        ramal: 4811,
        email: "lucas.mendonca@mhedica.com.br",
        numero: 31983999710,
        cargo: "Gerente de Vendas",
        setor: "Vendas",
        admissao: "01/10/2020",
        aniversario: "11/26/1991",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/lucas-mendonca.png?alt=media&token=f09819cc-b781-46af-ae4a-f5a3f3e07a1e",
    },
    {
        chave: "luiz-claudio",
        nome: "Luiz",
        sobrenome: "Claudio",
        ramal: 4796,
        email: "luizclaudio.viana@mhedica.com.br",
        numero: 31972501112,
        cargo: "Analista de Logística Jr",
        setor: "Estoque",
        admissao: "05/10/2022",
        aniversario: "01/13/1978",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/lucas-claudio.png?alt=media&token=5dca560d-fb5a-4f61-96dd-507f6a2843ee",
    },
    {
        chave: "marcos-faria",
        nome: "Marcos",
        sobrenome: "Faria",
        ramal: 4807,
        email: "marcos.faria@mhedica.com.br",
        numero: 31995403565,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "25/10/2021",
        aniversario: "11/19/1984",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/marcos-faria.png?alt=media&token=1a6f7466-f45a-4bed-b36c-d85341d8f766",
    },
    {
        chave: "marcos-ferreira",
        nome: "Marcos",
        sobrenome: "Ferreira",
        ramal: 4798,
        email: "marcos@mhedica.com.br",
        numero: 31983840430,
        cargo: "Especialista de Produtos Pleno",
        setor: "Comercial",
        admissao: "31/08/2020",
        aniversario: "03/09/1986",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/marcos-ferreira.png?alt=media&token=cd9b051c-772b-4d6c-a3d2-a7287754b059",
    },
    {
        chave: "marcos-oliveira",
        nome: "Marcos Vinicius",
        sobrenome: "Oliveira",
        ramal: 4805,
        email: "almoxarifado@mhedica.com.br",
        numero: 31984826796,
        cargo: "Analista de Logística Jr",
        setor: "Almoxarifado",
        admissao: "05/10/2022",
        aniversario: "06/03/1983",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/marcos-oliveira.png?alt=media&token=ccaa8b0e-ff45-42f5-aa30-dcd825a303e1",
    },
    {
        chave: "marcus-fantoni",
        nome: "Marcus",
        sobrenome: "Fantoni",
        ramal: 4807,
        email: "marcus.fantoni@mhedica.com.br",
        numero: 31984666714,
        cargo: "Gerente de Vendas Imagem",
        setor: "Vendas",
        admissao: "15/09/2021",
        aniversario: "03/26/1970",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/marcus-fantoni.png?alt=media&token=6334d3bb-d3d3-448b-944f-98e4fa3d85d2",
    },
    {
        chave: "mercia",
        nome: "Mércia",
        sobrenome: "Carmo",
        ramal: 4815,
        email: "qualidade@mhedica.com.br",
        numero: 31990606312,
        cargo: "Responsável Técnica | Farmaceutica",
        setor: "Qualidade",
        admissao: "07/02/2022",
        aniversario: "05/04/1982",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/mercia.png?alt=media&token=9642e464-dfdd-407c-924e-ff509c71ad1c",
    },
    {
        chave: "napoleao",
        nome: "Napoleão",
        sobrenome: "Sorbello",
        ramal: 4794,
        email: "napoleao@mhedica.com.br",
        numero: 31984826747,
        cargo: "CEO",
        setor: "Diretoria",
        admissao: null,
        aniversario: "03/16/1956",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/napoleao.png?alt=media&token=5cd31933-cab2-48b3-b5e5-11b853226ecd",
    },
    {
        chave: "nayara",
        nome: "Nayara",
        sobrenome: "Fuchs",
        ramal: 4803,
        email: "nayara@mhedica.com.br",
        numero: 31984827062,
        cargo: "Gerente Comercial",
        setor: "Comercial",
        admissao: "05/11/2014",
        aniversario: "08/07/1983",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/nayara.png?alt=media&token=acabe293-79c4-49dd-ae14-809bd192ce9c",
    },
    {
        chave: "paulo",
        nome: "Paulo",
        sobrenome: "Lucas",
        ramal: 4804,
        email: "paulo@mhedica.com.br",
        numero: 31995994810,
        cargo: "Auxiliar de TI",
        setor: "TI",
        admissao: "14/02/2022",
        aniversario: "11/28/2001",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/paulo.png?alt=media&token=a4a96a84-0de3-42ea-8728-a195ef843efc",
    },
    {
        chave: "poliana",
        nome: "Poliana",
        sobrenome: "Candelária",
        ramal: 4813,
        email: "poliana@mhedica.com.br",
        numero: 31984664732,
        cargo: "Analista de Licitação",
        setor: "Comercial",
        admissao: "08/11/2021",
        aniversario: "02/05/1988",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/poliana.png?alt=media&token=cfc71a93-a297-40d0-9223-e7fb516a7135",
    },
    {
        chave: "rafael-danilo",
        nome: "Rafael",
        sobrenome: "Danilo",
        ramal: 4814,
        email: "rafael.danilo@mhedica.com.br",
        numero: 31996002877,
        cargo: "Especialista Fiscal",
        setor: "Comercial",
        admissao: "23/11/2021",
        aniversario: "01/25/1991",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/rafael-danilo.png?alt=media&token=208f14c6-6846-4eec-b841-b122c234045f",
    },
    {
        chave: "rafael-sorbello",
        nome: "Rafael",
        sobrenome: "Sorbello",
        ramal: 4793,
        email: "rafael@mhedica.com.br",
        numero: 31984543952,
        cargo: "Diretor de Vendas",
        setor: "Diretoria",
        admissao: null,
        aniversario: "04/28/1982",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/rafael-sorbello.png?alt=media&token=5863b9e0-7f48-42e6-83bd-9b0c5c8678b5",
    },
    {
        chave: "rafaela",
        nome: "Rafaela",
        sobrenome: "Santos",
        ramal: 4807,
        email: "rafaela@mhedica.com.br",
        numero: 31998007520,
        cargo: "Especialista de Produtos",
        setor: "Especialista",
        admissao: "11/02/2019",
        aniversario: "08/10/1989",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/rafaela.png?alt=media&token=210c248b-c17e-4c2d-a18e-12d469b0f65a",
    },
    {
        chave: "ricardo",
        nome: "Ricardo",
        sobrenome: "Dutra",
        ramal: 4810,
        email: "ricardo@mhedica.com.br",
        numero: 31984826706,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "03/02/2020",
        aniversario: "01/18/1976",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/ricardo.png?alt=media&token=a347100e-8b43-450b-9918-d54943a3bb8c",
    },
    {
        chave: "rubens",
        nome: "Rubens",
        sobrenome: "Bentes",
        ramal: 4809,
        email: "rubens@mhedica.com.br",
        numero: 31990606251,
        cargo: "Técnico Junior 2",
        setor: "Assistência Técnica",
        admissao: "31/01/2022",
        aniversario: "08/05/1986",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/rubens.png?alt=media&token=1b96b3b2-b0a8-4053-936e-fd7ac1dd0046",
    },
    {
        chave: "rudson",
        nome: "Rudson",
        sobrenome: "Ribeiro",
        ramal: null,
        email: "rudson@mhedica.com.br",
        numero: 31984826738,
        cargo: "Diretor de Vendas",
        setor: "Vendas",
        admissao: "12/11/2012",
        aniversario: "11/03/1981",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/rudson.png?alt=media&token=0b043f5e-4e1b-48e9-865b-1768a4c3272b",
    },
    {
        chave: "sidney",
        nome: "Sidney",
        sobrenome: "Castro",
        ramal: 4807,
        email: "sidney@mhedica.com.br",
        numero: 31998500345,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "14/10/2021",
        aniversario: "10/19/1976",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/sidney.png?alt=media&token=f2020a9a-de96-47c3-81a2-f8b1921a303a",
    },
    {
        chave: "silvia",
        nome: "Silvia",
        sobrenome: "Paixão",
        ramal: 4802,
        email: "silvia@mhedica.com.br",
        numero: 31996987518,
        cargo: "Supervisora Comercial",
        setor: "Comercial",
        admissao: "08/09/2017",
        aniversario: "04/30/1979",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/silvia.png?alt=media&token=08c8137c-873b-49a1-a450-0d0a541edf4e",
    },
    {
        chave: "stefanie",
        nome: "Stefanie",
        sobrenome: "Sorbello",
        ramal: 4797,
        email: "stefanie@mhedica.com.br",
        numero: 31984826926,
        cargo: "Diretora de Operações",
        setor: "Diretoria | Comercial",
        admissao: null,
        aniversario: "10/06/1986",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/stefanie.png?alt=media&token=fb66b28d-0315-4463-8699-70a38f3b8037",
    },
    {
        chave: "thais",
        nome: "Thais",
        sobrenome: "Barroso",
        ramal: "Sem Ramal",
        email: "thais@mhedica.com.br",
        numero: 31984001861,
        cargo: "Consultora de Vendas",
        setor: "Vendas",
        admissao: "05/10/2020",
        aniversario: "12/09/1994",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/thais.png?alt=media&token=2f079692-24e5-4bad-9182-3cad10709a67",
    },
    {
        chave: "victor-hugo",
        nome: "Victor",
        sobrenome: "Hugo",
        ramal: 4792,
        email: "victor@mhedica.com.br",
        numero: 31984826752,
        cargo: "Técnico Junior 2",
        setor: "Assistência Técnica",
        admissao: "01/08/2009",
        aniversario: "11/19/1977",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/victor-hugo.png?alt=media&token=02c0b081-fec8-4f70-92cd-3cf5e5b5297c",
    },
    {
        chave: "victor-ferreira",
        nome: "Victor",
        sobrenome: "Ferreira",
        ramal: 4812,
        email: "victor.ferreira@mhedica.com.br",
        numero: 31996761564,
        cargo: "Gerente de Imagem",
        setor: "Vendas",
        admissao: "03/10/2022",
        aniversario: "02/20/1996",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/victor-paulo.png?alt=media&token=03405629-4c3a-44ed-97e1-137242f577ca",
    },
    {
        chave: "wander",
        nome: "Wander",
        sobrenome: "Amendoeira",
        ramal: 4812,
        email: "wander@mhedica.com.br",
        numero: 31997414354,
        cargo: "Consultor de Vendas",
        setor: "Vendas",
        admissao: "05/10/2020",
        aniversario: "12/26/1962",
        foto: "https://firebasestorage.googleapis.com/v0/b/fotos-funcionarios-mhedica.appspot.com/o/wander.png?alt=media&token=7248f98b-65c8-4e83-98ba-91e71300c163",
    },
    
]

export const grupos = [
    {
        key: ["brenda", "fernanda-rodrigues", "rafaela"],
        grupo: "Especialistas",
        email: "especialistas@mhedica.com.br",
        membros: [" Brenda", " Fernanda Rodrigues", " Rafaela"]
    },
    {
        key: ["claudio", "douglas", "eduardo-benedicto", "fabio", "jacimara", "juan", "larissa","rubens", "victor"],
        grupo: "Chamado",
        email: "chamado@mhedica.com.br",
        membros: [" Claudio", " Douglas", " Eduardo Benedicto", " Fabio", " Jacimara", " Juan", " Larissa"," Rubens", " Victor"]
    },
    {
        key: ["aline", "carlos", "elizangela", "gabriella", "marcos-ferreira", "nayara", "poliana", "rafael-danilo", "silvia", "stefanie", "jane", "mercia", "marcos-oliveira", "leticia", "eduardo-rangel", "lucas-henrique", "luiz-claudio" ],
        grupo: "Comercial",
        email: "comercial@mhedica.com.br",
        membros: [" Aline", " Carlos", " Elizangela", " Gabriella"," Marcos Ferreira", " Nayara", " Poliana", " Rafael Danilo", " Silvia", " Stefanie", " Jane", " Mércia", " Marcos Oliveira", " Leticia", " Eduardo Rangel", " Lucas Henrique", " Luiz Claudio"]
    },
    {
        key: ["rafael-danilo", "stefanie", "silvia", "leticia"],
        grupo: "Compras Nacionais",
        email: "comprasnacionais@mhedica.com.br",
        membros: [" Rafael Danilo", " Stefanie", " Silvia", " Leticia"]
    },
    {
        key:["claudio", "douglas", "stefanie"],
        grupo: "Compras Importação",
        email: "comprasimportacao@mhedica.com.br",
        membros: [" Claudio", "Douglas", " Stefanie"]
    },
    {
        key: ["douglas", "napoleao", "rafael-sorbello", "stefanie"],
        grupo: "Diretoria",
        email: "diretoria@mhedica.com.br",
        membros: [" Douglas", " Napoleão", " Rafael Sorbello", " Stefanie"]
    },
    {
        key: ["marcos-oliveira","luiz-claudio", "eduardo-rangel", "lucas-henrique"],
        grupo: "Estoque",
        email: "estoque@mhedica.com.br",
        membros: [" Marcos Oliveira", " Luiz Claudio",  " Eduardo Rangel", " Lucas Henrique"]
    },
    {
        key: ["aline", "antonio", "brenda", "carlos", "bruno-varandas", "italo", "claudio", "cileia", "douglas", "eduardo-benedicto", "eugenio", "elizangela", "fabio", "fernanda-moreira", "fernanda-rodrigues", "mercia", "gabriella", "glauber", "glauciene", "jacimara", "jane", "juan", "larissa", "leticia","lucas-araujo", "marcos-oliveira", "lucas-mendonca", "luana-morelle", "marcos-ferreira", "marcos-faria", "marcus.fantoni", "napoleao", "nayara", "paulo", "poliana", "rafael-sorbello", "rafael-danilo", "rafaela", "ricardo", "rubens", "rudson", "sidney", "silvia", "stefanie", "thais", "victor-hugo", "victor-ferreira","wander","luiz-claudio", "eduardo-rangel", "lucas-henrique"],
        grupo: "Geral",
        email: "geral@mhedica.com.br",
        membros: [" Aline", " Brenda", " Bruno Varandas", " Carlos", " Claudio", " Cileia", " Douglas", " Eduardo Benedicto", " Eduardo Rangel", " Eugênio", " Elizangela", " Fabio", " Fernanda Moreira", " Fernanda Rodrigues", " Mércia", " Gabriella", " Glauber", " Glauciene", " Ítalo"," Jacimara", " Jane", " Juan", " Larissa", " Leticia", " Lucas Araújo", "Lucas Mendonça", " Lucas Henrique", " Marcos Oliveira", " Luiz Claudio", " Luana Morelle", " Marcos Ferreira", " Marcos Faria", " Marcus Fantoni", " Napoleão", " Nayara", " Paulo", " Poliana", " Rafael Sorbello", " Rafael Danilo", " Rafaela", " Ricardo", " Rubens", " Rudson", " Sidney", " Silvia", " Stefanie", " Thais", " Victor Hugo", " Victor Ferreira", " Wander"]
    },
    {
        key: ["glauciene", "stefanie", "fernanda-moreira"],
        grupo: "Financeiro",
        email: "financeiro@mhedica.com.br",
        membros: [" Glauciene", " Stefanie", " Fernanda Moreira"]
    },
    {
        key: ["carlos", "stefanie", "napoleao", "nayara"],
        grupo: "Pedido",
        email: "pedido@mhedica.com.br",
        membros: [" Carlos", " Stefanie", " Napoleão", " Nayara"]
    },
    {
        key:["carlos", "elizangela", "gabriella", "napoleao", "nayara"],
        grupo: "Proposta",
        email: "proposta@mhedica.com.br",
        membros: [" Carlos", " Elizangela", " Gabriella", " Napoleão", " Nayara"]
    },
    {
        key:["aline", "marcos-oliveira", "lucas-henrique", "eduardo-rangel", "luiz-claudio", "leticia", "glauciene", "stefanie", "fernanda-moreira", "silvia", "nayara", "mercia", "rafael-danilo"],
        grupo: "Recebimento NFe",
        email: "recebimentonfe@mhedica.com.br",
        membros: [" Aline", " Marcos Oliveira", " Lucas Henrique", " Eduardo Rangel", " Luiz Claudio", " Letícia", " Glauciene", " Stefanie", " Fernanda Moreira", " Silvia", " Nayara", " Mércia", " Rafael Danilo"]
    },
    {
        key: ["antonio","bruno-varandas", "glauber", "lucas-araujo", "lucas-mendonca", "marcos-faria", "marcus-fantoni", "napoleao", "rafael-sorbello", "ricardo", "sidney", "thais", "victor-ferreira", "wander"],
        grupo: "Vendas",
        email: "vendas@mhedica.com.br",
        membros: [" Antônio"," Bruno Varandas", " Glauber", " Lucas Araujo", " Lucas Mendonça", " Marcos Faria", " Marcus Fantoni", " Napoleão", " Rafael Sorbello", " Ricardo", " Sidney", " Thais", " Victor Ferreira", " Wander"]
    }
]